[package]
name = "rust-actix-boilerplaite"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "cmd/server/main.rs"

[dependencies]
actix-web = "4"
config = { path = "config" }
internal = { path = "internal" }
dependencies = { path = "dependencies" }

