services:
  app:
    container_name: app_service
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    ports:
      - '8080:8080'
    restart: unless-stopped
    depends_on:
      - appdb
    networks:
      - postgres_db-manager

  appdb:
    image: postgres:16-alpine
    container_name: app_db
    env_file: env/.db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5434:5432'
    networks:
      - postgres_db-manager

volumes:
  postgres_data:

networks:
  postgres_db-manager:
    external: true