[package]
name = "internal"
version = "0.1.0"
edition = "2021"

[lib]
name = "internal"
path = "internal.rs"

[dependencies]
config = { path = "../config" }
dependencies = { path = "../dependencies" }
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
diesel = { version = "2.2.0", features = ["postgres", "chrono", "r2d2"] }
diesel_migrations = { version = "2.2.0" }
chrono = { version = "0.4.38", features = ["serde"] }